apiVersion: v1
kind: Pod
metadata:
  name: update-checker
  labels:
    app: update-checker
spec:
  containers:
  - name: kubectl
    image: nginx
    command:
    - sh
    - -c
    - |
    - nginx -v
